apiVersion: 1
contactPoints:
    - orgId: 1
      name: Discord Notifications
      receivers:
        - uid: dfrtxn9zhsa9se
          type: discord
          settings:
            url: $DISCORD_WEBHOOK_URL
            use_discord_username: false
          disableResolveMessage: false
