name: Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on:
      - self-hosted
      - deployment-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show machine info
        shell: powershell -ExecutionPolicy Bypass -File {0}
        run: |
          Write-Host "Runner is working!"
          hostname
          whoami
          Get-Location